name = "LShapedSolvers"
uuid = "c132518a-c710-11e8-267a-6b0667a43ff3"
authors = ["Martin Biel <martinbiel93@gmail.com>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StochasticPrograms = "da0032aa-aa18-11e8-3e9c-4127ef7a7461"
TraitDispatch = "a073c066-aa1c-11e8-2535-2def105228db"

[extras]
GLPKMathProgInterface = "3c7084bd-78ad-589a-b5bb-dbd673274bea"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Logging", "GLPKMathProgInterface", "Ipopt"]
